### ISSUE TITLE
Added a new library; pip install needs to be run everytime on root login

### ISSUE THREAD

**Issue by gmsk19** [regisb/openedx-docker#25]
Hi,
      I just added a new library bcrypt by doing  a pip install. I also included the dependency in edx-platform/requirements/edx/base.txt . After that I quit my terminal.
When i freshly tried to do a 'make cms' followed by ./manage.py cms runserver, it throws a dependency error. Of course if I do call pip install brcypt again, it works as a charm.

I understand that there is a platform/requirements/edx/development.txt , should i include the brcypt dependency there and run 'pip install -r requirements/edx/development.txt' everytime before i run the server .  is base.txt only meant for production.
What i expected was that if i include the dependency in some txt file under requirements, I would not have to run pip install manually again.

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
Hi Shashi,

The problem that you are facing is not that base.txt is used only for production. You must understand how Docker works: the command `pip install -r requirements/base.txt` is only run once, during the build step of the Docker image. At that point, your custom `base.txt` file is not present in the container, because the stock ginkgo version of edx-platform is used. Then, even if you run `pip install bcrypt` inside the container, the installed bcrypt will not persist for the next run because Docker containers are stateless.

There are different solutions to your problem:
1. You can run `pip install bcrypt` every time you start your container, but that is rather boring.
1. You can add a custom line `RUN pip install bcrypt` inside the `openedx/Dockerfile` file, towards the end. For instance, right after the "# Copy convenient scripts" section. Then run  `make build` on the host: the docker container will then have your custom requirements.

Please answer with your selected answer and close this issue if it solved your problem.

**Comment by gmsk19** [comment]
Dear Regis,
             Thank for the detailed answer. I have been using option 1 as of now as a hack. I shall try the second option and close the issue.

**Comment by gmsk19** [comment]
Dear Regis,
               The Second option works . Thanks for the valuable information shared.

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
Great!
