### ISSUE TITLE
"creating new user 'openedx' with UID" takes a long time

### ISSUE THREAD

**Issue by dannielarriola** [regisb/openedx-docker#39]
This happens when I recreate the images or when I create a staff user

Is there any way to avoid this?

**Comment by regisb** [comment]
A new user is created so that files generated by the containers have the same user ID as the user that launch the commands on thehost. What takes time is not so much the user creation but the `chown -R` command that follows: https://github.com/regisb/openedx-docker/blob/master/openedx/bin/docker-entrypoint.sh#L12 Speed depends on the speed of your hard disk (I guess...).

To avoid this step, just set the USERID environment variable to 0:

    export USERID=0
    make lms
    ...

**Comment by dannielarriola** [comment]
Great, Thanks
