### ISSUE TITLE
Running on HTTPS and Production

### ISSUE THREAD

**Issue by gmsk19** [regisb/openedx-docker#46]
Dear Regis,
                   How can we run this deployment on SSL/Https. Also I have to run edx on production server, would opened-docker based deployment suffice or are  any additional servers like nginx/apache2 required.

With Regards,
Shashi Kiran G M

**Comment by tony-h** [comment]
You can add the SSL certs directly in the edx stack. It's kind of a pain. Below is what I did to get it to work. The better option that I found is to use NGINX as a reverse proxy and leave the edx configs alone. https://tylermade.net/2017/09/14/the-perfect-reverse-proxy-nginx-ssl-webui-management/ 
Take your pick.

```
# add default certs (or copy the real certs)
mkdir ~/openedx-docker/data/lms/certs
mkdir ~/openedx-docker/data/cms/certs
cp /etc/ssl/certs/ssl-cert-snakeoil.pem ~/openedx-docker/data/lms/certs/fullchain.pem
cp /etc/ssl/private/ssl-cert-snakeoil.key ~/openedx-docker/data/lms/certs/privkey.pem
cp /etc/ssl/certs/ssl-cert-snakeoil.pem ~/openedx-docker/data/cms/certs/fullchain.pem
cp /etc/ssl/private/ssl-cert-snakeoil.key ~/openedx-docker/data/cms/certs/privkey.pem
  
# Copy configs and add 443 SSL support
cp ~/openedx-docker/config/nginx/lms.conf ~/openedx-docker/config/nginx/lms-ssl.conf
cp ~/openedx-docker/config/nginx/cms.conf ~/openedx-docker/config/nginx/cms-ssl.conf

nano ~/openedx-docker/config/nginx/lms-ssl.conf
  listen 443 ssl;
  ssl_certificate     /openedx/data/lms/certs/fullchain.pem;
  ssl_certificate_key /openedx/data/lms/certs/privkey.pem;

nano ~/openedx-docker/config/nginx/cms-ssl.conf
  listen 443 ssl;
  ssl_certificate     /openedx/data/cms/certs/fullchain.pem;
  ssl_certificate_key /openedx/data/cms/certs/privkey.pem;
```

**Comment by regisb** [comment]
Thanks @tony-h for your thorough answer!
@gmsk19 I am fully aware that SSL certificates are a crucial feature for a production platform. When I created this project I thought it would be better simply to provide instructions on how to install certificates rather than have an optional SSL feature flag which would have made the 1-click install more complex and opaque. This opinion was reflected in that disclaimer: https://github.com/regisb/openedx-docker#ssl-certificates
However, I now think it should be possible to produce SSL certificates rather easily, post-install. I still need to work out the details, though. So I'm going to leave this issue open until I find an easy way to generate and update certificates. Meanwhile, @tony-h's instructions should work.

**Comment by gmsk19** [comment]
Dear @regisb  and @tony-h  
                        Thanks for sharing the information. I shall try out tony's recommendations and revert back.

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
Good news! This is now a feature of the latest release. Just run:

    ACTIVATE_HTTPS=1 make all

instead of `make all`.

More information [in the readme](https://github.com/regisb/openedx-docker#ssltls-certificates-for-https-access-activate_https).
