### ISSUE TITLE
HTTPs installation 

### ISSUE THREAD

**Issue by shohrehahvar** [regisb/openedx-docker#66]
Hello,

Thanks again for your support.

Please in my node.js file, I need to have access to APIs which need authentication such as /api/user/v1/accounts

Please I have several stupid questions in this regards :D

0-I should take oath2 token from my instance ?  
1- I need to have https edx for that ? or without https should work?  (because without https, /oauth2/v1/access_token will not be loaded)

2- you said download the certificates manually, You mean : 

2-1 If I install your edx in a VM on my laptop and I do "make https-certificate", then  ACTIVATE_HTTPS=1 make all, it will be fine? Sorry I did not get it.
Or
2-2 If I install your edx in a VM in azure  and I do make "https-certificate", then ACTIVATE_HTTPS=1 make all, it will be fine?

I get error for make https-certificate:

911c6d0c7995: Pull complete
a14b79d248fe: Pull complete
978b0814e03c: Pull complete
b9571a6eb4fc: Pull complete
8dbac7cc55d3: Pull complete
453638fb1731: Pull complete
8dbd3ea36d85: Pull complete
7f1bcecfb3ae: Pull complete
667252cfad2e: Pull complete
2bc6e7e64635: Pull complete
Status: Downloaded newer image for certbot/certbot:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/openedx/letsencrypt/config/certonly.sh\": stat /openedx/letsencrypt/config/certonly.sh: no such file or directory": unknown.
ERRO[0020] error waiting for container: context canceled
Makefile:103: recipe for target 'https-certificate' failed
make: *** [https-certificate] Error 127

Or
2-3 If I install edx in a VM in azure  and I do  ACTIVATE_HTTPS=1 make all, it should work?

2-4 anyway, this time I installed your edx on an azure VM with using 
I clone ur edx and then sudo ACTIVATE_HTTPS=1 make all 
and I left the CMS, LMS related questions on default (i.e., www.myopenedx.com, ...)
Nothing else :D
I got this error : 

error : Status: Downloaded newer image for certbot/certbot:latest

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator standalone, Installer None

Unable to register an account with ACME server

Makefile:103: recipe for target 'https-certificate' failed

make: *** [https-certificate] Error 1

Thanks for your help. I'm blocked :(

Best regards,

**Comment by regisb** [comment]
0. > I should take oath2 token from my instance ?

I don't know, it depends what your requirements are.

1. > I need to have https edx for that ? or without https should work? (because without https, /oauth2/v1/access_token will not be loaded)

You need to add the `OAUTH_ENFORCE_SECURE = False` setting to allow oauth2 over http.

21. > If I install your edx in a VM on my laptop and I do "make https-certificate", then ACTIVATE_HTTPS=1 make all, it will be fine?

No. `make https-certificate` on your laptop *will not work*. That's because the DNS record for your domain name does not point to your VM. Do you know how DNS works?

22. > If I install your edx in a VM in azure and I do make "https-certificate", then ACTIVATE_HTTPS=1 make all, it will be fine?\

Yes, it should, provided the right DNS records point to your server.

Make sure to run `ACTIVATE_HTTPS=1 make configure` prior to `make https-certificate`.

23. > If I install edx in a VM in azure and I do ACTIVATE_HTTPS=1 make all, it should work?

Yes, it should, provided the right DNS records point to your server.

24. > anyway, this time I installed your edx on an azure VM with using I clone ur edx and then sudo ACTIVATE_HTTPS=1 make all and I left the CMS, LMS related questions on default (i.e., www.myopenedx.com, ...)

:weary:  This will not work because the www.myopenedx.com domain name record does not point to your VM.

**Comment by shohrehahvar** [comment]
Thanks again for your helo. One question please:
in your git you wrote  for SSL we should run ACTIVATE_HTTPS=1 make all and in the issue you wrote ACTIVATE_HTTPS=1 make configure .
So which one ? I guess ACTIVATE_HTTPS=1 make configure , yes?
I just clone and I run ACTIVATE_HTTPS=1 make configure ?

so my VM name in Azure is  http://sho.northeurope.cloudapp.azure.com/
so I run ACTIVATE_HTTPS=1 make configure and 
I set LMS as sho.northeurope.cloudapp.azure.com?
CMS will be review.sho.northeurope.cloudapp.azure.com automatically 
after running make https-certificate I reveive the error as follows for be review.sho.northeurope.cloudapp.azure.com. 
Cleaning up challenges
Failed authorization procedure. studio.sho.northeurope.cloudapp.azure.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for studio.sho.northeurope.cloudapp.azure.com, preview.sho.northeurope.cloudapp.azure.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for preview.sho.northeurope.cloudapp.azure.com
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: studio.sho.northeurope.cloudapp.azure.com
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up A for
   studio.sho.northeurope.cloudapp.azure.com

   Domain: preview.sho.northeurope.cloudapp.azure.com
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up A for
   preview.sho.northeurope.cloudapp.azure.com
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
Makefile:117: recipe for target 'https-certificate' failed
make: *** [https-certificate] Error 1


So I should have another VM referring to review.sho.northeurope.cloudapp.azure.com ? and for studio.sho.northeurope.cloudapp.azure.com as well another one?

Thanks,

Best regards,
