### ISSUE TITLE
Question: What about preview.edxhostname?

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#77]
Hi,
When you are using studio to preview problems you just made, it sends you to preview.edx.fweb.wallawalla.edu in your browser in my case, which does not exist.   Do I need to point DNS to that, and forward a port for that as well, or what?  How is the preview supposed to work?
Thanks,
Rob

**Comment by tony-h** [comment]
> Do I need to point DNS to that, and forward a port for that as well

Correct. You have to add a DNS setting for `preview.edx.fweb.wallawalla.edu` that points to the same IP address as `edx.fweb.wallawalla.edu`. Because you are using Apache to forward the ports, you will need to either (a) add `preview.edx.fweb.wallawalla.edu` as an alias to `edx.fweb.wallawalla.edu` or (b) create a new conf file for the `preview.edx.fweb.wallawalla.edu` subdomain name. I don't know how Apache handles forwarding proxied domain names. I think an alias should work. Also, see #55.

**Comment by frohro** [comment]
So it looks to me like that just defaults "Preview" to the same thing "Live View" gives.  This doesn't really bother me, but it seems like in wasn't what "Preview" was originally supposed to be.  Am I misunderstanding things?

Thanks for your quick answers.  :-)
Rob

**Comment by regisb** [comment]
Yes, I agree it's kind of strange. Note for instance that it's possible to access edx.org from the "preview" subdomain : https://preview.edx.org/dashboard
The LMS detects that you are accessing it from the preview hostname and only displays some portion of the content.
You made me realise that the `preview.localhost` hostname was not configured, so I'm going to fix this.
