### ISSUE TITLE
Restarting lms cms and workers

### ISSUE THREAD

**Issue by frob** [regisb/openedx-docker#91]
I am pretty new to EdX, most of the documentation and support I have read says to restart the app with commands like:

```bash
/edx/bin/supervisorstl -c /edx/etc/supervisord.conf restart edxapp:
```

I am curious if there is an easy way to do this to a container running in the daemon mode? Can this be run on the docker app without restarting the docker containers as a whole?

**Comment by regisb** [comment]
With docker containers, there is no more need for external supervision. Instead, supervision is handled by docker-compose. To answer your question: no, there is no way to restart the app without restarting the container. This is by design: each container contains just a single process, so containers are very well compartimentalized (is that a word?).

So you want to run:

    docker-compose restart lms

And probably:

        docker-compose restart lms_worker

And maybe:

    docker-compose restart cms
    docker-compose restart cms_worker

    docker-compose restart cms

**Comment by frob** [comment]
Yup this works. Sorry I didn't notice this (face palm). I ran 

```
docker-compose restart lms lms_worker cms cms_worker
```

Would you be opposed to me putting this into a make command? `make restart` or `make restart-app`

**Comment by regisb** [comment]
> Would you be opposed to me putting this into a make command? make restart or make restart-app

The thing is that "restart" is misleading: for instance, when we make changes to the docker-compose.yml file, "restart" [does not load the changes](https://docs.docker.com/compose/reference/restart/). 

Nonetheless, it's a useful command. Maybe add `make restart-openedx `?

**Comment by frob** [comment]
I am new to EdX so I will let you name the command something that makes sense. `make restart-openedx` it is.
